### ISSUE TITLE
[TEST] Rancher integration test failed on cypress test

### ISSUE THREAD

**Issue by khushboo-rancher** [harvester/tests#1197]
## What's the test to develop? Please describe

Below test cases failed on cypress test

- [x] Rancher First Login
- [x] Rancher import Harvester
- [x] Harvester import Rancher
- [x] Check Harvester Cluster Status
- [x] Check Rancher Harvester dashboard

**Comment by khushboo-rancher** [comment]
@TachunLin Please add logs for the test cases if you have them

**Comment by TachunLin** [comment]
For test plan `Rancher import Harvester`, according to the [test result](https://minio.provo.rancherlabs.com:31524/cypress-test-report/cypress/results/20240329-061037-1747c15/index.html) 

* The failure log indicate can't find the `#username` field, this is caused by the previous test failure
```
AssertionError: Timed out retrying after 240000ms: Expected to find element: `#username`, but never found it.
    at rancherPage.login (webpack:///./pageobjects/rancher.po.ts:148:11)
    at rancherPage.rancherLogin (webpack:///./pageobjects/rancher.po.ts:160:13)
    at Context.eval (webpack:///./testcases/rancher/rancher_integration.spec.ts:113:16)
```

* The failure screenshot
![image](https://github.com/harvester/tests/assets/29251855/b71a5be5-c6c7-4d8e-b339-701413240190)


* The failure comes from the following lines of code 
  - File: `../cypress/testcases/rancher/rancher_integration.spec.ts`
  - Line: https://github.com/harvester/tests/blob/1747c1598b79047aaa261e9fa7fd2c626d4af0a9/cypress/testcases/rancher/rancher_integration.spec.ts#L115-L120

**Comment by TachunLin** [comment]
For test plan `Harvester import Rancher`, according to the [test result](https://minio.provo.rancherlabs.com:31524/cypress-test-report/cypress/results/20240329-061037-1747c15/index.html) 

* The failure log indicate the globalVar.trim is not a function, probably caused by the cypress or typescript version 
```
TypeError: globalVar.trim is not a function
    at Context.eval (webpack:///./pageobjects/rancher.po.ts:212:46)
```

* The failure screenshot
![image](https://github.com/harvester/tests/assets/29251855/e5dd03b5-3420-40bc-820a-305aafa71943)


* The failure comes from the following lines of code 
  - File: `../cypress/testcases/rancher/rancher_integration.spec.ts`
  - Line: https://github.com/harvester/tests/blob/1747c1598b79047aaa261e9fa7fd2c626d4af0a9/cypress/testcases/rancher/rancher_integration.spec.ts#L133-L136

**Comment by TachunLin** [comment]
For test plan `Check Harvester Cluster Status`, according to the [test result](https://minio.provo.rancherlabs.com:31524/cypress-test-report/cypress/results/20240329-061037-1747c15/index.html) 

* The failure log indicate can't find the #username field, this is caused by the previous test failure 
```
AssertionError: Timed out retrying after 240000ms: Expected to find element: `#username`, but never found it.
    at rancherPage.login (webpack:///./pageobjects/rancher.po.ts:148:11)
    at rancherPage.rancherLogin (webpack:///./pageobjects/rancher.po.ts:160:13)
    at Context.eval (webpack:///./testcases/rancher/rancher_integration.spec.ts:143:16)
```

* The failure screenshot
![image](https://github.com/harvester/tests/assets/29251855/53e9f878-3ffe-43ff-ad1f-c4e8fdf13183)


* The failure comes from the following lines of code 
  - File: `../cypress/testcases/rancher/rancher_integration.spec.ts`
  - Line: https://github.com/harvester/tests/blob/1747c1598b79047aaa261e9fa7fd2c626d4af0a9/cypress/testcases/rancher/rancher_integration.spec.ts#L139-L147

**Comment by TachunLin** [comment]
According to the latest daily cypress test on the main Jenkins 

In the cypress test result, currently the first three issues have been fixed

1.  Rancher First Login
2. Rancher import Harvester
3. Harvester import Rancher

![image](https://github.com/harvester/tests/assets/29251855/c0899274-eab6-4e29-8ad3-8588a38bbc80)

For the last two failed cases, the test script itself works as expected. 
While the remote test environment have problem to import Harvester to Rancher 

Finding on the Harvester stide, the cattle-cluster-agent pod keep in CrashLoopBackOff failure
![image](https://github.com/harvester/tests/assets/29251855/d5a1c5c0-6c11-4ef4-8d03-5d18530d3732)

The pod log display the error message
```
time="2024-05-21T12:57:51Z" level=error msg="Issuer of last certificate found in chain (CN=dynamiclistener-ca@1716280612,O=dynamiclistener-org) does not m │
│ atch with CA certificate Issuer (CN=dynamiclistener-ca@1716280610,O=dynamiclistener-org). Please check if the configured server certificate contains all n │
│ eeded intermediate certificates and make sure they are in the correct order (server certificate first, intermediates after)"                               │
│ time="2024-05-21T12:57:51Z" level=fatal msg="Certificate chain is not complete, please check if all needed intermediate certificates are included in the s │
│ erver certificate (in the correct order) and if the cacerts setting in Rancher either contains the correct CA certificate (in the case of using self signe │
│ d certificates) or is empty (in the case of using a certificate signed by a recognized CA). Certificate information is displayed above. error: Get \"https │
│ ://172.19.104.190\": tls: failed to verify certificate: x509: certificate signed by unknown authority"
```

It maybe related to the certificate issue in the environment.
On the way to check whether it caused by lacking some helm install chart option

**Comment by TachunLin** [comment]
According to the test result in https://github.com/harvester/harvester-baremetal-ansible/pull/46 

Tested on the main Jenkins jobs
http://jenkins.provo.rancherlabs.com/job/harvester-cypress-test/48/

There can pass all the existing Rancher integration cypress tests in test report
https://minio.provo.rancherlabs.com:31524/cypress-test-report/cypress/results/20240527-033831-70bf60c/index.html

![image](https://github.com/harvester/tests/assets/29251855/aa446f99-c557-4ce4-a3b6-cca94e41e329)


All the failed Rancher integration test cases have been fixed.
