### ISSUE TITLE
[Release Test] Negative node un-schedulable during live migration

### ISSUE THREAD

**Issue by albinsun** [harvester/tests#1322]
## Step
1. Cluster is of 3 nodes.
1. VM is running on Node-1 with some test data
1. Set condition to let Node-2 and Node-3 are invalid for VM migration.
1. Migrate the VM.

## Expected Results
1. Migration should not start or fail.
1. The existing VM should still be accessible and healthy.

## Scenarios
1. Via PCI device @noahgildersleeve 
1. Via node affinity @albinsun 

cc. @khushboo-rancher

**Comment by albinsun** [comment]
## Scenario: Node Affinity
### Step
1. :green_circle: Setup 3 nodes cluster with with different label `topology.kubernetes.io/zone`
   * <details>
     <summary> <code>node-0</code> (<code>topology.kubernetes.io/zone: zone0</code>)
     </summary>

     ![image](https://github.com/harvester/tests/assets/2773781/8b72cfd8-36ce-41ab-8469-3e2b4d8ca757)
     </details> 
   * <details>
     <summary> <code>node-1</code> (<code>topology.kubernetes.io/zone: zone1</code>)
     </summary>

     ![image](https://github.com/harvester/tests/assets/2773781/af1e0199-964a-403a-b159-dc7a5dd9aa1d)
     </details>   
   * <details>
     <summary> <code>node-2</code> (Witness node)
     </summary>

     ![image](https://github.com/harvester/tests/assets/2773781/2b92f21e-cb96-4cde-ab9d-b99eed02a336)
     </details> 

1. :green_circle: Create VM `vm-zone0` with node affinity and test data
   <details>
   
   ![image](https://github.com/harvester/tests/assets/2773781/ed5aa635-9a75-44a8-a48c-1b2e2c3dfe4f)
   </details>

1. :green_circle: `vm-zone0` should running on `node-0`
   <details>
   
   ![image](https://github.com/harvester/tests/assets/2773781/85881bee-7710-449c-bb6e-fa0d0dfa1724)
   </details>

1. :green_circle: Cordon `node-0`
   <details>

   ![image](https://github.com/harvester/tests/assets/2773781/944551d0-56ac-4051-809d-8989598ac389)
   </details>

1. :green_circle: Migration should not start or fail.
   ![image](https://github.com/harvester/tests/assets/2773781/72c6a106-c7fb-4b6f-9110-c22b3467fdc8)

1. :green_circle: The existing VM should still be accessible and healthy.
   ![image](https://github.com/harvester/tests/assets/2773781/3e92c2e4-259e-449e-afeb-7740144998e2)

1. :green_circle: Uncordon `node-0`
   <details>

   ![image](https://github.com/harvester/tests/assets/2773781/8d678aed-09ef-4eaf-92df-0ab3a878ba0b)
   </details>
  
1. :green_circle: The existing VM should still be accessible and healthy.
   ![image](https://github.com/harvester/tests/assets/2773781/8dc56505-c628-4eaf-a8d6-10d3ede1bc29)

**Comment by ibrokethecloud** [comment]
This is expected behaviour. The maintenance operation is trigger by an annotation on the node object.

Once node is drained successfully, and placed in maintenance mode, the annotation requesting drain is removed, and a completion annotation is added, which enables the UI element for disable maintenance.

In this case, the VM cannot be migrated as a result maintenance request is never completed. 

Uncordoning the node will not remove the annotation, and user needs to edit the node yaml and remove the annotation, as we have not yet got to the state where completion annotation is present, which in turn drives the disable maintenance UI element.

This is expected behaviour, and has been around since v1.2.x

Please remove the annotation: `"harvesterhci.io/drain-requested": "true"` from node to ensure the controller stops its attempts to place node in maintenance mode.

**Comment by w13915984028** [comment]
@ibrokethecloud Could you add the explanation to document https://docs.harvesterhci.io/v1.3/host/#node-maintenance, thanks.

Meanwhile,  it seems the `Maintenance` mode is lack of a `failed` status which can clearly show  that entering the maintenance mode failed due to some reasons like certain VM can never be migrated.
