### ISSUE TITLE
[TEST] Run Harvester Rancher integration with Rancher 2.8.7

### ISSUE THREAD

**Issue by khushboo-rancher** [harvester/tests#1528]
## What's the test to develop? Please describe

Let's use the Ci to run Rancher tests with Harvester 1.3.2 and Rancher 2.8.7

The scenarios to be tested:
1. Creation of rke1/rke2 guest clusters.
2. Verifying the charts. Cloud provider, CSI driver
4. Scale up and down the clusters.
5. Upgrading rke2 guest clusters.
6. Deleting the clusters.
7. Upgrading Rancher from 2.8.6 -> 2.8.7
8. Upgrading Rancher from 2.7.15 to -> 2.8.7

**Comment by m-ildefons** [comment]
| Test                                             | RKE v1.28 | RKE v1.27 |
| ------------------------------------------------ | --------- | --------- |
| Creating RKE 1/2                                 | :green_circle: |  |
| Verifying the charts. Cloud provider, CSI driver | | |
| Scale up and down the clusters                   | | |
| Upgrading rke2 guest clusters                    | N/A | |
| Deleting the clusters                            | :green_circle: |  |
| Upgrading Rancher from 2.8.6 -> 2.8.7            | | |
| Upgrading Rancher from 2.7.15 to -> 2.8.7        | N/A | |

**Comment by khushboo-rancher** [comment]
>Verifying the charts. Cloud provider, CSI driver

This should be covered in the Rancher integration automated test cases runs in the pipeline.

**Comment by m-ildefons** [comment]
Creating/deleting RKE1 and RKE2 clusters is covered in the e2e test suite. But I'm not sure that verifying charts is. Which tests cover that?

**Comment by khushboo-rancher** [comment]
For RKE1 guest cluster, below are the test cases
`test_cloud_provider_chart, test_deploy_nginx, test_load_balancer_service, test_csi_driver_chart, test_csi_deployment`

For RKE2, the charts are bundled and available as soon as cluster is up, below test cases run to check the functionality.
    `test_deploy_nginx, test_load_balancer_service, test_csi_deployment, test_create_pvc`

**Comment by m-ildefons** [comment]
@khushboo-rancher are there any limitations that I'm not aware of when it comes to scaling RKE guest clusters? Apart from RKE2 v1.27, my testing went awful, so I'm starting to doubt that I did this correctly.

For all guest clusters under test, I configured one machine pool with each machine in that pool being a control-plane node. Then I changed the machine count of the pool from 1 to 2 to 3 and back to 2 and finally back to 1. Waiting for the cluster to stabilize each time.
As a result, when scaling the count of etcd machines changes. This isn't problematic for scaling up, but when scaling down this leads to a loss of quorum of the etcd cluster. I assumed that Rancher would take care of restoring quorum in this case and it does seem to work for RKE2 v1.27. But RKE1 v1.27 and RKE2 v1.28 are both failing with errors relating to loss of quorum on etcd. Also both failed when scaling from 2 to 1. Since quorum for a three node cluster is 2/3, I'm starting to think that scaling down below the minimum required for quorum at the maximum machine count messes up the guest cluster generally and maybe isn't supported at all?
Maybe scaling down only really works for exclusive worker nodes, i.e. when the count of etcd nodes doesn't change?

RKE1 v1.28 failed to even scale up, during the registration phase of K8s, but I'm not sure if this is just flaky or what.

We also don't have any automated scaling tests or any documented test procedures for the scaling of guest clusters. I asked the rancher team if they have done any testing in this area, perhaps on other cloud providers and if there is anything I can look at for reference, but I'm still waiting for an answer.

**Comment by khushboo-rancher** [comment]
As far I know, Scaling down directly from 3 to 1 should work but 3 to 2 might have some problem but I'm not sure. For our testing, we can just add worker node for scaling up/down test scenario. I'll document it in detail in our test repo.

**Comment by albinsun** [comment]
May relates to https://github.com/rancher/rancher/issues/42582.
Which fix in _v2.9_ but not in _v2.8_

**Comment by m-ildefons** [comment]
I've had quite a bit of conversation with some Rancher QA folks yesterday and bottom line is that any configuration with 2 control plane/etcd nodes (even temporarily) is not supported. Since I was using the UI to initiate scaling, I was temporarily running with 2 guest nodes. This means my tests were flawed and so are the results. I'll try if scaling directly works, but otherwise I'll have to redesign the test scenario, e.g.:
1 etcd/cp, 1 worker --> 1 etcd/cp, 3 worker --> 1 etcd/cp, 1 worker

There is a case to be made here that Rancher shouldn't allow a user to break their cluster in this way without a warning, but that's a Rancher issue and has nothing to do with Harvester.

@albinsun I believe I saw the corresponding [Harvester bug](https://github.com/harvester/harvester/issues/4358) but the cluster ended up recovering after some time.

**Comment by khushboo-rancher** [comment]
Thanks @m-ildefons, closing this as the testing is completed.
